- name: Setup lab and deploy SONiC containerlab nodes
  hosts: localhost
  become: false
  tasks:

    - name: git pull to update repo on localhost
      command: git pull
      args:
        chdir: /home/cisco/sonic-dcloud
      ignore_errors: yes

- name: Run deploy playbook
  import_playbook: lab_deploy-playbook.yml
  ignore_errors: yes
