# ansible-playbook -i hosts lab_deploy-playbook.yml -e "ansible_user=cisco ansible_ssh_pass=cisco123 ansible_sudo_pass=cisco123" -vv
      
- name: Copy motd to endpoint VMs
  hosts: endpoint_vms
  become: true
  tasks:
    - name: Copy motd file to remote vm
      copy:
        src: "motd"
        dest: "/etc/motd"
        mode: 0644 

- name: Start logging VXR and sonic build status to deploy.log file
  hosts: localhost
  become: false
  tasks:
      
    - name: deploy.log start message
      become: false
      lineinfile:
        path: "/home/cisco/deploy.log"
        line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: Start sonic 8000e VXR deploy script"
        create: yes
      delegate_to: localhost
      
    - name: deploy.log time to spin up
      become: false
      lineinfile:
        path: "/home/cisco/deploy.log"
        line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: Expect to wait 10+ minutes as VXR scripts build out SONiC routers"
        create: yes
      delegate_to: localhost
      
- name: Setup lab using vxr.py to deploy SONiC nodes
  hosts: localhost
  become: true
  tasks: 
    - name: Copy motd file to linux-host-1
      copy:
        src: "motd"
        dest: "/etc/motd"
        mode: 0644 
      
    - name: run VXR start on linux-host-1 to launch sonic 8000 emulator nodes - this will take about 6 minutes
      command: "sudo vxr.py start 4-node-topo.yaml"
      args:
        chdir: /home/cisco/sonic-dcloud/2-SONiC_102/vxr/
      ignore_errors: yes
      #register: vxr_out

    - name: deploy.log VXR status
      become: false
      lineinfile:
        path: "/home/cisco/deploy.log"
        line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: VXR script complete, now pausing for 4 minutes for Onie/SONiC build"
        create: yes
      delegate_to: localhost

    - name: pause for 15 seconds to let vxr start script change sonic nodes' mgt IPs from dhcp to static
      pause:
        seconds: 15
      become: false

    - name: reset user/group permissions on repo folders 
      command: "chown -R cisco:cisco /home/cisco/sonic-dcloud"
      ignore_errors: yes

    - name: pause for 4 minutes while sonic nodes complete their build and interface assignments
      pause:
        minutes: 4
      become: false

- name: Check each SONiC Router's Management Interface
  hosts: localhost
  tasks:

  # STATUS LOGGING TO DEPLOY.LOG FILE
  - name: Post Start Health Check Script to Log
    lineinfile:
      path: "/home/cisco/deploy.log"
      line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: Running ping tests for sonic mgt interfaces"
      create: yes
      
  # Check sonic-rtr-leaf-1 mgt interface
  - name: Ping test sonic-rtr-leaf-1
    shell: ping -c 1 -W 5 192.168.122.101
    register: ping_result1
    ignore_errors: true

  - name: Conditional check if ping to sonic-rtr-leaf-1 failed
    block:
      - name: Output to deploy log file sonic-rtr-leaf-1 mgt interface
        lineinfile:
          path: "/home/cisco/deploy.log"
          line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}} {{ping_result1.stdout}}:
           Unable to ping sonic-rtr-leaf-1 mgt interface"
          create: yes

      - name: Print debug output sonic-rtr-leaf-1 interface
        debug:
          msg: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}} {{ping_result1.stdout}}: 
          Unable to ping sonic-rtr-leaf-1 mgt interface"
    when: (ping_result1.failed == true)

  - name: Conditional check if ping to sonic-rtr-leaf-1 success
    block:
      - name: Output to deploy log file sonic-rtr-leaf-1 ping status
        lineinfile:
          path: "/home/cisco/deploy.log"
          line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}} {{ping_result1.stdout}}: 
          sonic-rtr-leaf-1 has correct mgt interface"
          create: yes

      - name: print debug
        debug:
          msg: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}} {{ping_result1.stdout}}: 
          sonic-rtr-leaf-1 has correct mgt interface"

    when: (ping_result1.failed == false)

  # Check sonic-rtr-leaf-2 mgt interface
  - name: Ping test sonic-rtr-leaf-2
    shell: ping -c 1 -W 5 192.168.122.102
    register: ping_result2
    ignore_errors: true

  - name: Conditional check if ping to sonic-rtr-leaf-2 failed
    block:
      - name: Output to deploy log file
        lineinfile:
          path: "/home/cisco/deploy.log"
          line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}} {{ping_result2.stdout}}: 
          Unable to ping sonic-rtr-leaf-2 mgt interface"
          create: yes

      - name: Print debug output sonic-rtr-leaf-2 status
        debug:
          msg: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}} {{ping_result2.stdout}}: 
          Unable to ping sonic-rtr-leaf-2 mgt interface"   
    when: (ping_result2.failed == true)

  - name: Conditional check if ping to sonic-rtr-leaf-2 success
    block:
      - name: Output to deploy log file  sonic-rtr-leaf-2 status
        lineinfile:
          path: "/home/cisco/deploy.log"
          line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}} {{ping_result2.stdout}}: 
          sonic-rtr-leaf-2 has correct mgt interface"
          create: yes

      - name: print debug
        debug:
          msg: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}} {{ping_result2.stdout}}: 
          sonic-rtr-leaf-2 has correct mgt interface"

    when: (ping_result2.failed == false)

  # Check sonic-rtr-spine-1 mgt interface
  - name: Ping test sonic-rtr-spine-1
    shell: ping -c 1 -W 5 192.168.122.103
    register: ping_result3
    ignore_errors: true

  - name: Conditional check if ping to sonic-rtr-spine-1 failed
    block:
      - name: Output to deploy log file sonic-rtr-spine-1 status
        lineinfile:
          path: "/home/cisco/deploy.log"
          line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}} {{ping_result3.stdout}}: 
          Unable to ping sonic-rtr-spine-1 mgt interface
          "
          create: yes

      - name: Print debug output sonic-rtr-spine-1 status
        debug:
          msg: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}} {{ping_result3.stdout}}: 
          Unable to ping sonic-rtr-spine-1 mgt interface
          "
    when: (ping_result3.failed == true)

  - name: Conditional check if ping to sonic-rtr-spine-1 success
    block:
      - name: Output to deploy log file sonic-rtr-spine-1 status
        lineinfile:
          path: "/home/cisco/deploy.log"
          line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}} {{ping_result3.stdout}}: 
          sonic-rtr-spine-1 has correct mgt interface
          "
          create: yes

      - name: print debug
        debug:
          msg: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}} {{ping_result3.stdout}}: 
          sonic-rtr-spine-1 has correct mgt interface
          "

    when: (ping_result3.failed == false)

  # Check sonic-rtr-spine-2 mgt interface
  - name: Ping test sonic-rtr-spine-2
    shell: ping -c 1 -W 5 192.168.122.104
    register: ping_result4
    ignore_errors: true

  - name: Conditional check if ping to sonic-rtr-spine-2 failed
    block:
      - name: Output to deploy log file sonic-rtr-spine-2 status
        lineinfile:
          path: "/home/cisco/deploy.log"
          line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}} {{ping_result4.stdout}}:
          Unable to ping sonic-rtr-spine-2 mgt interface
          "
          create: yes

      - name: Print debug output sonic-rtr-spine-2 status
        debug:
          msg: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}} {{ping_result4.stdout}}: 
          Unable to ping sonic-rtr-spine-2 mgt interface
          "
    when: (ping_result4.failed == true)

  - name: Conditional check if ping to sonic-rtr-spine-2 success
    block:
      - name: Output to deploy log file sonic-rtr-spine-2 status
        lineinfile:
          path: "/home/cisco/deploy.log"
          line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}} {{ping_result4.stdout}}: 
          sonic-rtr-spine-2 has correct mgt interface
          "
          create: yes

      - name: print debug
        debug:
          msg: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}} {{ping_result4.stdout}}: 
          sonic-rtr-spine-2 has correct mgt interface
          "

    when: (ping_result4.failed == false)

- name: verify sonic routers have loaded 8000e interfaces
  hosts: sonic_routers
  vars:
      time_date:
        tz: ansible_date_time.tz
        date: ansible_date_time.date
        time: ansible_date_time.time
  tasks:
    - name: show interfaces status
      command: show interfaces status
      ignore_errors: yes
      register: show_int_status
      
    - name: Save interfaces status to local log file
      become: false
      lineinfile:
        path: "/home/cisco/deploy.log"
        line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: SONiC Router {{ inventory_hostname }} {{ show_int_status.stdout }}"
        #line: "{{ time_date[date] }} {{ time_date[time] }} {{ time_date[tz] }}: SONiC Router {{ inventory_hostname }} {{ show_int_status.stdout }}"
        create: yes
      delegate_to: localhost

    - name: VXR deploy complete
      become: false
      lineinfile:
        path: "/home/cisco/deploy.log"
        line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: Deploy script complete for {{ inventory_hostname }}"
        create: yes
      delegate_to: localhost

- name: Run deploy all playbook and import base configuration
  import_playbook: lab_base_config-playbook.yml
  ignore_errors: yes
