# ansible-playbook -i hosts lab_exercise_all-playbook.yml -e "ansible_user=cisco ansible_ssh_pass=cisco123 ansible_sudo_pass=cisco123" -vv

- name: Run deploy playbook
  import_playbook: lab_deploy-playbook.yml
  ignore_errors: yes

- name: Run lab 2 "config_db baseline" playbook
  import_playbook: lab_exercise_2-playbook.yml
  ignore_errors: yes

- name: run lab 3 "frr bgp" playbook
  import_playbook: lab_exercise_3-playbook.yml
  ignore_errors: yes

- name: run sonic-rtr-leaf-1 playbook
  import_playbook: other-playbooks/sonic-rtr-leaf-1-playbook.yml
  ignore_errors: yes
