---

# ansible-playbook -i hosts lab_deploy-playbook.yml -e "ansible_user=cisco ansible_ssh_pass=cisco123 ansible_sudo_pass=cisco123" -vv
      
- name: Start logging to deploy.log file
  hosts: localhost
  become: false
  tasks:
    - name: delete old deploy log 
      command: rm /home/cisco/deploy.log
      ignore_errors: yes
      run_once: true
      become: false
      delegate_to: localhost
      
    - name: deploy.log start message
      become: false
      lineinfile:
        path: "/home/cisco/deploy.log"
        line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: Start Containerlab Deploy Script"
        create: yes
      delegate_to: localhost
      
    - name: deploy.log time to spin up
      become: false
      lineinfile:
        path: "/home/cisco/deploy.log"
        line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: Expect to wait 10+ minutes as VXR scripts build out SONiC routers"
        create: yes
      delegate_to: localhost
      
- name: Setup lab using vxr.py to deploy SONiC nodes
  hosts: localhost
  become: true
  tasks: 
    - name: Copy motd file to linux-host-1
      copy:
        src: "motd"
        dest: "/etc/motd"
        mode: 0644 
      
    - name: run VXR start on linux-host-1 to launch sonic 8000 emulator nodes - this will take about 6 minutes
      command: "sudo vxr.py start 4-node-topo.yaml"
      args:
        chdir: /home/cisco/sonic-dcloud/1-SONiC_101/vxr/
      ignore_errors: yes

    - name: reset user/group permissions on repo folders 
      command: "chown -R cisco:cisco /home/cisco/sonic-dcloud"
      ignore_errors: yes

    - name: ping sonic leaf-1 management IP
      command: "ping 192.168.122.101 -c 2"
      ignore_errors: yes

    - name: ping sonic leaf-2 management IP
      command: "ping 192.168.122.102 -c 2"
      ignore_errors: yes

    - name: ping sonic spine-1 management IP
      command: "ping 192.168.122.103 -c 2"
      ignore_errors: yes

    - name: ping sonic spine-2 management IP
      command: "ping 192.168.122.104 -c 2"
      ignore_errors: yes

- name: Pause for 4 minutes then check sonic VMs interface status
  hosts: localhost
  tasks:
    - name: pause  
      pause:
        minutes: 4
      become: false

- name: verify sonic routers' health status
  hosts: sonic_routers
  tasks:
    - name: show interfaces status
      command: show interfaces status
      ignore_errors: yes
      register: show_int_status
      
    - name: Save interfaces status to local log file
      become: false
      lineinfile:
        path: "/home/cisco/sonic-dcloud/1-SONiC_101/vxr/deploy.log"
        line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: SONiC Router {{ inventory_hostname }} {{ show_int_status.stdout }}"
        create: yes
      delegate_to: localhost

# - name: run health check playbook
#   import_playbook: sonic_node_health_check.yml
#   ignore_errors: yes

- name: Setup lab and deploy endpoint nodes
  hosts: endpoint_vms
  become: true
  tasks:
    - name: Copy motd file to remote vm
      copy:
        src: "motd"
        dest: "/etc/motd"
        mode: 0644 
