---

# ansible-playbook -i hosts lab_exercise_2-playbook.yml -e "ansible_user=cisco ansible_ssh_pass=cisco123 ansible_sudo_pass=cisco123" -vv

- name: Apply baseline config to SONiC routers, and install nano
  hosts: sonic_routers
  become: true
  tasks:

    - name: Copy config_baseline.json files
      copy:
        src: "{{ inventory_hostname }}/config_baseline.json"
        dest: "/etc/sonic/config_baseline.json"
        mode: 0644

    - name: sonic config load
      command: "sudo config load /etc/sonic/config_baseline.json -y"
      ignore_errors: yes

    # - name: Load configuration
    #   expect:
    #     command: sudo config load /etc/sonic/config_baseline.json
    #     responses:
    #       (.*)y/N(.*): "y"
    #     timeout: 90
    #   ignore_errors: yes
    #   register: load_result

    - name: restart hostname service
      command: sudo systemctl restart hostname-config
      ignore_errors: yes

    - name: Copy loopback shell script
      copy:
        src: "{{ inventory_hostname }}/loopback.sh"
        dest: "/etc/sonic/loopback.sh"
        mode: 0755

    - name: run loopback shell script
      command: "/etc/sonic/loopback.sh"
      ignore_errors: yes

    - name: Save sonic configuration
      command: "sudo config save -y"
      ignore_errors: yes

    # - name: Save sonic configuration
    #   expect:
    #     command: sudo config save
    #     responses:
    #       (.*)y/N(.*): "y"
    #     timeout: 90
    #   ignore_errors: yes
    #   register: save_result

    - name: backup old debian apt sources.list
      command: "sudo mv /etc/atp/sources.list /etc/atp/sources.list.bak"
      ignore_errors: yes

    - name: Copy debian apt sources.list file
      copy:
        src: "{{ inventory_hostname }}/sources.list"
        dest: "/etc/apt/sources.list"
        mode: 0644

    - name: run apt update
      command: "sudo apt update"
      ignore_errors: yes

    - name: apt install nano
      command: "sudo apt install nano -y"
      ignore_errors: yes
