# ansible-playbook sonic_node_health_check.yml -e "ansible_user=cisco ansible_ssh_pass=cisco123 ansible_sudo_pass=cisco123" -vv

- name: Check each SONiC Router's Health
  hosts: localhost

  tasks:
  # Clear sonic router ssh keys from jumpbox
  - name: clear old ssh keys on jumpbox
    command: "rm /home/cisco/.ssh/known_hosts"
    ignore_errors: true

  # START LOGGING TO DEPLOY.LOG FILE
  - name: Post Start Health Check Script to Log
    lineinfile:
      path: "/home/cisco/deploy.log"
      line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: Running SONiC Router Health Check Script"
      create: yes
      
  # CHECK SONiC ROUTER sonic-rtr-leaf-1 STATUS
  - name: Ping test sonic-rtr-leaf-1
    shell: ping -c 1 -W 5 192.168.122.101
    register: ping_result1
    ignore_errors: true

  - name: Conditional check if ping to sonic-rtr-leaf-1 failed
    block:
      - name: Output to deploy log file sonic-rtr-leaf-1 status
        lineinfile:
          path: "/home/cisco/deploy.log"
          line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: SONiC Router sonic-rtr-leaf-1: Failed. Queued for rebuild."
          create: yes

      - name: Print debug output sonic-rtr-leaf-1 status
        debug:
          msg: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: SONiC Router sonic-rtr-leaf-1: Failed. Queued for rebuild."

      - name: Add linux-host-1 to host group sonic_node_rebuild
        add_host:
          name: '198.18.128.101'
          groups: sonic_node_rebuild

    when: (ping_result1.failed == true)

  - name: Conditional check if ping to sonic-rtr-leaf-1 success
    block:
      - name: Output to deploy log file sonic-rtr-leaf-1 status
        lineinfile:
          path: "/home/cisco/deploy.log"
          line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: SONiC Router sonic-rtr-leaf-1: Health Check Passed"
          create: yes

      - name: print debug
        debug:
          msg: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: SONiC Router sonic-rtr-leaf-1: Health Check Passed"

    when: (ping_result1.failed == false)

  # CHECK SONiC ROUTER sonic-rtr-leaf-2 STATUS
  - name: Ping test sonic-rtr-leaf-2
    shell: ping -c 1 -W 5 192.168.122.102
    register: ping_result2
    ignore_errors: true

  - name: Conditional check if ping to sonic-rtr-leaf-2 failed
    block:
      - name: Output to deploy log file
        lineinfile:
          path: "/home/cisco/deploy.log"
          line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: SONiC Router sonic-rtr-leaf-2: Failed. Queued for rebuild."
          create: yes

      - name: Print debug output sonic-rtr-leaf-2 status
        debug:
          msg: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: SONiC Router sonic-rtr-leaf-2: Failed. Queued for rebuild."

      - name: Add linux-host-2 to host group sonic_node_rebuild
        add_host:
          name: '198.18.128.102'
          groups: sonic_node_rebuild
          
    when: (ping_result2.failed == true)

  - name: Conditional check if ping to sonic-rtr-leaf-2 success
    block:
      - name: Output to deploy log file  sonic-rtr-leaf-2 status
        lineinfile:
          path: "/home/cisco/deploy.log"
          line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: SONiC Router sonic-rtr-leaf-2: Health Check Passed"
          create: yes

      - name: print debug
        debug:
          msg: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: SONiC Router sonic-rtr-leaf-2: Health Check Passed"

    when: (ping_result2.failed == false)

  # CHECK SONiC ROUTER sonic-rtr-spine-1 STATUS
  - name: Ping test sonic-rtr-spine-1
    shell: ping -c 1 -W 5 192.168.122.103
    register: ping_result3
    ignore_errors: true

  - name: Conditional check if ping to sonic-rtr-spine-1 failed
    block:
      - name: Output to deploy log file sonic-rtr-spine-1 status
        lineinfile:
          path: "/home/cisco/deploy.log"
          line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: SONiC Router sonic-rtr-spine-1: Failed. Queued for rebuild."
          create: yes

      - name: Print debug output sonic-rtr-spine-1 status
        debug:
          msg: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: SONiC Router sonic-rtr-spine-1: Failed. Queued for rebuild."

      - name: Add linux-host-3 to host group sonic_node_rebuild
        add_host:
          name: '198.18.128.103'
          groups: sonic_node_rebuild

    when: (ping_result3.failed == true)

  - name: Conditional check if ping to sonic-rtr-spine-1 success
    block:
      - name: Output to deploy log file sonic-rtr-spine-1 status
        lineinfile:
          path: "/home/cisco/deploy.log"
          line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: SONiC Router sonic-rtr-spine-1: Health Check Passed."
          create: yes

      - name: print debug
        debug:
          msg: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: SONiC Router sonic-rtr-spine-1: Health Check Passed."

    when: (ping_result3.failed == false)

  # CHECK SONiC ROUTER sonic-rtr-spine-2 STATUS
  - name: Ping test sonic-rtr-spine-2
    shell: ping -c 1 -W 5 192.168.122.104
    register: ping_result4
    ignore_errors: true

  - name: Conditional check if ping to sonic-rtr-spine-2 failed
    block:
      - name: Output to deploy log file sonic-rtr-spine-2 status
        lineinfile:
          path: "/home/cisco/deploy.log"
          line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: SONiC Router sonic-rtr-spine-2: Failed. Queued for rebuild."
          create: yes

      - name: Print debug output sonic-rtr-spine-2 status
        debug:
          msg: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: SONiC Router sonic-rtr-spine-2: Failed. Queued for rebuild."

      - name: Add linux-host-4 to host group sonic_node_rebuild
        add_host:
          name: '198.18.128.104'
          groups: sonic_node_rebuild

    when: (ping_result4.failed == true)

  - name: Conditional check if ping to sonic-rtr-spine-2 success
    block:
      - name: Output to deploy log file sonic-rtr-spine-2 status
        lineinfile:
          path: "/home/cisco/deploy.log"
          line: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: SONiC Router sonic-rtr-spine-2: Health Check Passed."
          create: yes

      - name: print debug
        debug:
          msg: "{{ ansible_date_time.date }} {{ansible_date_time.time}} {{ansible_date_time.tz}}: SONiC Router sonic-rtr-spine-2: Health Check Passed."

    when: (ping_result4.failed == false)
