---
- name: Ping and run new task
  hosts: vm-leaf-2
  gather_facts: false 
  tasks:
    - name: Ping leaf-2
      ansible.builtin.shell:
        cmd: "ping leaf-2 -c 1"
      register: ping_result

    - name: Print the ping results
      debug:
        var: ping_result

- name: Conditional Playbook Execution
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Execute playbook based on condition
      block:
        - include: vm-leaf-2-playbook.yml
          when: "'Run playbook on ping failure' in ansible_play_names"