---
- name: Ping and run new task
  hosts: jumpbox
  gather_facts: false

  # tasks:
  #   - name: Ping IP address
  #     ping:
  #       host: 172.10.10.101
  #     register: ping_result

  #   - name: Run new task if ping fails
  #     debug:
  #       msg: "Ping failed, running new task"
  #     when: ping_result.failed

  # become: yes  

  tasks:
    - name: Ping all hosts
      ansible.builtin.shell:
        cmd: "ansible all -m ping"
      register: ping_result


    - name: Execute a command on failed hosts
      ansible.builtin.command:
        cmd: docker ps
      when: ping_result.failed
      register: container_check

    - name: Print the ping results
      debug:
        var: ping_result

    - name: Print docker ps result
      debug:
        var: container_check
