---

# ansible-playbook -i hosts test-playbook.yml -e "ansible_user=cisco ansible_ssh_pass=cisco123 ansible_sudo_pass=cisco123" -vv

- name: Enable FRR BFD daemon and configure BFD sessions
  hosts: sonic_router_subset
  become: true
  tasks:

  - name: Copy playbook to remote hosts
    copy:
      src: lab_exercise_5-playbook.yml
      dest: /home/cisco/lab_exercise_5-playbook.yml

  - name: Execute playbook on remote hosts
    command: ansible-playbook /home/cisco/lab_exercise_5-playbook.yml


