---

# ansible-playbook -i hosts leaf-1-recover.yml -e "ansible_user=cisco ansible_ssh_pass=cisco123 ansible_sudo_pass=cisco123" -vv

- name: Setup lab and deploy SONiC containerlab nodes
  hosts: vm-leaf-1
  become: true
  tasks:
    - name: git pull to update repo on each VM
      command: git pull
      args:
        chdir: /home/cisco/sonic-dcloud
      ignore_errors: yes
      
    - name: run containerlab deploy command to launch sonic vxr leaf-1
      command: sudo containerlab deploy -t vm-leaf-1/clab.yml"
      args:
        chdir: /home/cisco/sonic-dcloud/1-SONiC_101/ansible/files/
      ignore_errors: yes

    - name: run vxlan shell script to interconnect containerlab nodes across VMs
      command: "vm-leaf-1/vxlan.sh"
      args:
        chdir: /home/cisco/sonic-dcloud/1-SONiC_101/ansible/files/
      ignore_errors: yes

    - name: reset user/group permissions on repo folders 
      command: "chown -R cisco:cisco /home/cisco/sonic-dcloud"
      ignore_errors: yes

    - name: clear old ssh keys 
      command: "rm .ssh/known_hosts"
      args:
        chdir: /home/cisco/
      ignore_errors: yes

    - name: Pause for 5 minutes
      pause:
        minutes: 5

    - name: Wait for 'Router' to appear in logs
      shell: docker logs -t {{ hostvars[inventory_hostname]['container'] }} | grep Router
      register: grep_result
      until: grep_result.stdout_lines | length > 0
      retries: 18  # Number of times to retry
      delay: 30  # Delay between retries
      timeout: 600  # Maximum time to wait (in seconds) 
      
    - name: Save grep output to a local log file
      lineinfile:
        path: "/home/cisco/leaf-1-recover.log"
        line: "{{inventory_hostname}} {{ grep_result.stdout }}"
        create: yes
      delegate_to: localhost
      

