---

# ansible-playbook -i ../hosts sonic-rtr-leaf-1-playbook.yml -e "ansible_user=cisco ansible_ssh_pass=cisco123 ansible_sudo_pass=cisco123" -vv

- name: Apply config_db.json and FRR config to sonic-rtr-leaf-1 and install nano
  hosts: sonic-rtr-leaf-1
  become: true
  tasks:

    - name: Copy config_db.json file
      copy:
        src: "sonic-rtr-leaf-1/config_db.json"
        dest: "/etc/sonic/new_config_db.json"
        mode: 0644

    - name: Load configuration
      expect:
        command: sudo config load /etc/sonic/new_config_db.json
        responses:
          (.*)y/N(.*): "y"
        timeout: 90
      ignore_errors: yes
      register: load_result

    - name: restart hostname service
      command: sudo systemctl restart hostname-config
      ignore_errors: yes

    - name: Copy loopback shell script
      copy:
        src: "sonic-rtr-leaf-1/loopback.sh"
        dest: "/etc/sonic/loopback.sh"
        mode: 0755

    - name: run loopback shell script
      command: "/etc/sonic/loopback.sh"
      ignore_errors: yes

    - name: Save sonic configuration
      expect:
        command: sudo config save
        responses:
          (.*)y/N(.*): "y"
        timeout: 90
      ignore_errors: yes
      register: save_result

    - name: Copy nano-tiny debian package to VMs
      copy:
        src: "/home/cisco/packages/nano-tiny_3.2-3_amd64.deb"
        dest: "/var/cache/apt/archives/nano-tiny_3.2-3_amd64.deb"
        mode: 0644

    - name: apt install nano-tiny
      command: sudo apt-get install /var/cache/apt/archives/nano-tiny_3.2-3_amd64.deb -y
      ignore_errors: yes
      register: save_result

    - name: create nano binary from nano-tiny
      command: "sudo cp /usr/bin/nano-tiny /usr/local/bin/nano"
      ignore_errors: yes

    - name: Create a backup of the existing FRR file
      command: mv /etc/sonic/frr/bgpd.conf /etc/sonic/frr/bgpd.conf.bak
      args:
        creates: /etc/sonic/frr/bgpd.conf.bak
      ignore_errors: yes
      register: backup_result

    - name: Copy frr config files
      copy:
        src: "sonic-rtr-leaf-1/frr.conf"
        dest: "/etc/sonic/frr/bgpd.conf"
        mode: 0644

    - name: Stop BGP container
      command: docker stop bgp
      timeout: 20

    - name: Start BGP container
      command: docker start bgp
      timeout: 10