---

# ansible-playbook -i hosts launch-playbook.yml -e "ansible_user=cisco ansible_ssh_pass=C1sco12345 ansible_sudo_pass=C1sco12345" -vv

- name: Run git pull and containerlab deployments
  hosts: sonic_hosts
  become: true
  tasks:
    - name: git pull to update repo on each node
      command: git pull
      args:
        chdir: /home/cisco/sonic-dcloud
      ignore_errors: yes

    - name: run containerlab deploy
      command: sudo containerlab deploy -t "{{ inventory_hostname }}/clab.yml"
      args:
        chdir: /home/cisco/sonic-dcloud/1-Intro_to_SONiC_Lab/ansible/files/
      ignore_errors: yes

    - name: run vxlan shell script
      command: "{{ inventory_hostname }}/vxlan.sh"
      args:
        chdir: /home/cisco/sonic-dcloud/1-Intro_to_SONiC_Lab/ansible/files/
      ignore_errors: yes

    - name: clear old ssh keys
      command: "rm .ssh/known_hosts"
      args:
        chdir: /home/cisco/
      ignore_errors: yes


