---

# ansible-playbook -i hosts lab_deploy-playbook.yml -e "ansible_user=cisco ansible_ssh_pass=cisco123 ansible_sudo_pass=cisco123" -vv

- name: Run git pull and containerlab deployments
  hosts: sonic_host_vms
  become: true
  tasks:
    - name: git pull to update repo on each VM
      command: git pull
      args:
        chdir: /home/cisco/sonic-dcloud
      ignore_errors: yes

    - name: run containerlab deploy to launch sonic vxr8000 nodes
      command: sudo containerlab deploy -t "{{ inventory_hostname }}/clab.yml"
      args:
        chdir: /home/cisco/sonic-dcloud/1-Intro_to_SONiC_Lab/ansible/files/
      ignore_errors: yes

    - name: run vxlan shell script to interconnect containerlab nodes across VMs
      command: "{{ inventory_hostname }}/vxlan.sh"
      args:
        chdir: /home/cisco/sonic-dcloud/1-Intro_to_SONiC_Lab/ansible/files/
      ignore_errors: yes

    - name: clear old ssh keys 
      command: "rm .ssh/known_hosts"
      args:
        chdir: /home/cisco/
      ignore_errors: yes


