---
- name: Copy config_update.json to sonic routers and perform a config load command
  hosts: sonic_nodes
  become: true
  tasks:

    - name: Copy config_baseline.json files
      copy:
        src: "{{ inventory_hostname }}/config_baseline.json"
        dest: "/etc/sonic/config_baseline.json"
        mode: 0644

    - name: Load configuration
      expect:
        command: sudo config load /etc/sonic/config_baseline.json
        responses:
          (.*)y/N(.*): "y"
        timeout: 90
      ignore_errors: yes
      register: reload_result

    - name: Save configuration
      expect:
        command: sudo config save
        responses:
          (.*)y/N(.*): "y"
        timeout: 90
      ignore_errors: yes
      register: reload_result