---

# ansible-playbook -i hosts lab_exercise_2-playbook.yml -e "ansible_user=cisco ansible_ssh_pass=cisco123 ansible_sudo_pass=cisco123" -vv

- name: Apply baseline config to SONiC routers, and install nano
  hosts: sonic_routers
  become: true
  tasks:

    - name: Copy config_baseline.json files
      copy:
        src: "{{ inventory_hostname }}/config_baseline.json"
        dest: "/etc/sonic/config_baseline.json"
        mode: 0644

    - name: Load configuration
      expect:
        command: sudo config load /etc/sonic/config_baseline.json
        responses:
          (.*)y/N(.*): "y"
        timeout: 90
      ignore_errors: yes
      register: load_result

    - name: restart hostname service
      command: sudo systemctl restart hostname-config
      ignore_errors: yes

    - name: Copy loopback shell script
      copy:
        src: "{{ inventory_hostname }}/loopback.sh"
        dest: "/etc/sonic/loopback.sh"
        mode: 0755

    - name: run loopback shell script
      command: "/etc/sonic/loopback.sh"
      ignore_errors: yes

    - name: Save sonic configuration
      expect:
        command: sudo config save
        responses:
          (.*)y/N(.*): "y"
        timeout: 90
      ignore_errors: yes
      register: save_result

    - name: Copy nano-tiny debian package to VMs
      copy:
        src: "/home/cisco/images/nano-tiny_3.2-3_amd64.deb"
        dest: "/var/cache/apt/archives/nano-tiny_3.2-3_amd64.deb"
        mode: 0644

    - name: apt install nano-tiny
      command: sudo apt-get install /var/cache/apt/archives/nano-tiny_3.2-3_amd64.deb -y
      ignore_errors: yes
      register: save_result

    - name: create nano binary from nano-tiny
      command: "sudo cp /usr/bin/nano-tiny /usr/local/bin/nano"
      ignore_errors: yes