---

# ansible-playbook -i hosts test-playbook.yml -e "ansible_user=cisco ansible_ssh_pass=cisco123 ansible_sudo_pass=cisco123" -vv

- name: Setup lab and deploy SONiC containerlab nodes
  hosts: sonic_host_vms
  become: true
  tasks:

    - name: clear old ssh keys 
      command: "rm .ssh/known_hosts"
      args:
        chdir: /home/cisco/
      ignore_errors: yes

    # - name: Pause for 10 minutes
    #   pause:
    #     minutes: 10

    - name: Run a command and direct output to a log file
      command: "docker logs -f clab-c8201-sonic-{{hostvars[inventory_hostname][clab_container] }} | grep Router"
      args:
        # Add any arguments to your command here
      async: 600 # Set an async timeout (seconds) to allow the command to run for up to 10 minutes
      poll: 0    # Set poll to 0 to run the command asynchronously
      register: command_result

    - name: Wait for the command to complete
      async_status:
        jid: "{{ command_result.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 600  # Number of times to check the job status (600 * 1 second = 10 minutes)
      delay: 1      # Delay between retries (1 second)

    - name: Save command output to a log file
      copy:
        content: "{{ job_result.stdout }}"
        dest: /home/cisco/logfile.log