name: c8101-sonic

mgmt:
  network: mgt_net
  ipv4_subnet: 172.10.10.0/24
  bridge: sonic_mgt_br
  
topology:
  kinds:
    linux:
      image: c8000-clab-sonic:31
      binds: 
          - /home/cisco/images:/images
      env:
          IMAGE: /images/sonic-cisco-8000.bin
          PID: '8101-32H'

  nodes:

    leaf-2:
      kind: linux
      mgmt_ipv4: 172.10.10.102

    sonic_e32:
      kind: bridge

  links:

    - endpoints: ["leaf-2:eth1", "host:leaf-2-eth1"]
    - endpoints: ["leaf-2:eth2", "host:leaf-2-eth2"]

    - endpoints: ["leaf-2:eth3", "host:leaf-2-eth3"]
    - endpoints: ["leaf-2:eth4", "host:leaf-2-eth4"]

    - endpoints: ["leaf-2:eth9", "sonic_e32:leaf-2-eth9"]

