---
- name: Copy config_db.json and FRR configuration files to target hosts with backup and config reload
  hosts: sonic_nodes
  become: true
  tasks:

    - name: Copy config_baseline.json files
      copy:
        src: "{{ inventory_hostname }}/config_baseline.json"
        dest: "/etc/sonic/config_baseline.json"
        mode: 0644

    - name: Load configuration
      expect:
        command: sudo config load -y /etc/sonic/config_baseline.json
        timeout: 90
      ignore_errors: yes
      register: reload_result
