---

# ansible-playbook -i hosts lab_deploy-playbook.yml -e "ansible_user=cisco ansible_ssh_pass=C1sco12345 ansible_sudo_pass=C1sco12345" -vv

- name: Run git pull and containerlab deployments
  hosts: localhost
  become: true
  tasks:
    - name: git pull to update repo on each VM
      command: git pull
      args:
        chdir: /home/cisco/sonic-dcloud
      ignore_errors: yes

    - name: run containerlab deploy to launch sonic vxr8000 nodes
      command: sudo containerlab deploy -t clab-topology.yml
      args:
        chdir: /home/cisco/sonic-dcloud/4-node/ansible/
      ignore_errors: yes

    - name: clear old ssh keys 
      command: "rm .ssh/known_hosts"
      args:
        chdir: /home/cisco/
      ignore_errors: yes


