---
- name: Copy FRR config to hosts and perform config reload
  hosts: sonic_nodes
  become: true
  tasks:

    - name: Create a backup of the existing FRR file
      command: mv /etc/sonic/frr/bgpd.conf /etc/sonic/frr/bgpd.conf.bak
      args:
        creates: /etc/sonic/frr/bgpd.conf.bak
      ignore_errors: yes
      register: backup_result

    - name: Copy frr config files
      copy:
        src: "{{ inventory_hostname }}/frr.conf"
        dest: "/etc/sonic/frr/bgpd.conf"
        mode: 0644

    - name: Stop BGP container
      command: docker stop bgp
      timeout: 20

    - name: Start BGP container
      command: docker start bgp
      timeout: 10

    - name: Run 'docker ps' command
      become: true
      command: docker ps
      timeout: 15

    - name: Run 'ip route' command
      become: true
      command: ip route

    - debug: var=reload_result.stdout_lines

