---

# ansible-playbook -i hosts launch-playbook.yml -e "ansible_user=cisco ansible_ssh_pass=C1sco12345 ansible_sudo_pass=C1sco12345" -vv

- name: Run git pull and containerlab deployments
  hosts: sonic_nodes
  become: true
  tasks:
    - name: git pull to update repo on each node
      command: git pull
      args:
        chdir: /home/cisco/sonic-dcloud
      ignore_errors: yes

    - name: run containerlab deploy
      command: sudo containerlab deploy -t "files/{{ inventory_hostname }}/deploy.yml"
      # args:
      #   creates: /etc/sonic/frr/bgpd.conf.bak
      ignore_errors: yes
      register: backup_result


