---

# ansible-playbook -i hosts launch-playbook.yml -e "ansible_user=cisco ansible_ssh_pass=C1sco12345 ansible_sudo_pass=C1sco12345" -vv

- name: Run git pull and containerlab deployments
  hosts: sonic_nodes
  become: true
  tasks:
    - name: git pull to update repo on each node
      command: git pull
      args:
        chdir: /home/cisco/sonic-dcloud
      ignore_errors: yes

    - name: run containerlab deploy
      command: sudo containerlab deploy -t "{{ inventory_hostname }}/clab.yml"
      args:
        chdir: /home/cisco/sonic-dcloud/1-Intro_to_SONiC_Lab/util/ansible/files/
      ignore_errors: yes

    - name: run vxlan shell script
      command: "{{ inventory_hostname }}/vxlan.sh"
      args:
        chdir: /home/cisco/sonic-dcloud/1-Intro_to_SONiC_Lab/util/ansible/files/
      ignore_errors: yes

# - name: run clab vxlan commands on leaf-1
#   hosts: leaf-1
#   tasks:
#     - name: build leaf-1 to spine-1 vxlan 10
#       shell: sudo clab tools vxlan create --remote 172.10.10.103 --id 10 --link leaf-1-eth1
#       ignore_errors: yes

#     - name: build leaf-1 to spine-1 vxlan 20
#       command: sudo clab tools vxlan create --remote 172.10.10.103 --id 20 --link leaf-1-eth2

#     - name: build leaf-1 to spine-2 vxlan 30
#       shell: sudo clab tools vxlan create --remote 172.10.10.104 --id 30 --link leaf-1-eth3

#     - name: build leaf-1 to spine-2 vxlan 40
#       command: sudo clab tools vxlan create --remote 172.10.10.104 --id 40 --link leaf-1-eth4

# - name: run clab vxlan commands on leaf-2
#   hosts: leaf-2
#   tasks:
#     - name: build leaf-2 to spine-1 vxlan 10
#       command: sudo clab tools vxlan create --remote 172.10.10.104 --id 10 --link leaf-2-eth1

#     - name: build leaf-2 to spine-1 vxlan 20
#       command: sudo clab tools vxlan create --remote 172.10.10.104 --id 20 --link leaf-2-eth2

#     - name: build leaf-2 to spine-2 vxlan 30
#       command: sudo clab tools vxlan create --remote 172.10.10.103 --id 30 --link leaf-2-eth3

#     - name: build leaf-2 to spine-2 vxlan 40
#       command: sudo clab tools vxlan create --remote 172.10.10.103 --id 40 --link leaf-2-eth4

# - name: run clab vlan commands on leaf-1
#   hosts: leaf-1
#   tasks:
#     - name: build leaf-1 vxlans
#       shell: |
#         sudo clab tools vxlan create --remote 172.10.10.103 --id 10 --link leaf-1-eth1
#         sudo clab tools vxlan create --remote 172.10.10.103 --id 20 --link leaf-1-eth2
#         sudo clab tools vxlan create --remote 172.10.10.104 --id 30 --link leaf-1-eth3
#         sudo clab tools vxlan create --remote 172.10.10.104 --id 40 --link leaf-1-eth4

# - name: run clab vlan commands on leaf-2
#   hosts: leaf-2
#   tasks:
#     - name: build leaf-2 vxlans
#       shell: |
#         sudo clab tools vxlan create --remote 172.10.10.104 --id 10 --link leaf-2-eth1
#         sudo clab tools vxlan create --remote 172.10.10.104 --id 20 --link leaf-2-eth2
#         sudo clab tools vxlan create --remote 172.10.10.103 --id 30 --link leaf-2-eth3
#         sudo clab tools vxlan create --remote 172.10.10.103 --id 40 --link leaf-2-eth4

# - name: run clab vlan commands on spine-1
#   hosts: spine-1
#   tasks:
#     - name: build spine-1 vxlans
#       shell: |
#         sudo clab tools vxlan create --remote 172.10.10.101 --id 10 --link spine-1-eth1
#         sudo clab tools vxlan create --remote 172.10.10.101 --id 20 --link spine-1-eth2
#         sudo clab tools vxlan create --remote 172.10.10.102 --id 30 --link spine-1-eth3
#         sudo clab tools vxlan create --remote 172.10.10.102 --id 40 --link spine-1-eth4

# - name: run clab vlan commands on spine-2
#   hosts: spine-2
#   tasks:
#     - name: build spine-2 vxlans
#       shell: |
#         sudo clab tools vxlan create --remote 172.10.10.102 --id 10 --link spine-2-eth1
#         sudo clab tools vxlan create --remote 172.10.10.102 --id 20 --link spine-2-eth2
#         sudo clab tools vxlan create --remote 172.10.10.101 --id 30 --link spine-2-eth3
#         sudo clab tools vxlan create --remote 172.10.10.101 --id 40 --link spine-2-eth4


