---

# ansible-playbook -i hosts launch-playbook.yml -e "ansible_user=cisco ansible_ssh_pass=C1sco12345 ansible_sudo_pass=C1sco12345" -vv

- name: Run git pull and containerlab deployments
  hosts: sonic_nodes
  become: true
  tasks:
    - name: git pull to update repo on each node
      command: git pull
      args:
        chdir: /home/cisco/sonic-dcloud
      ignore_errors: yes

    - name: run containerlab deploy
      command: sudo containerlab deploy -t "{{ inventory_hostname }}/clab.yml"
      args:
        chdir: /home/cisco/sonic-dcloud/1-Intro_to_SONiC_Lab/util/ansible/files/
      ignore_errors: yes

    - name: build leaf-1 vxlans
      hosts: leaf-1
      shell: |
        sudo clab tools vxlan create --remote 172.10.10.103 --id 10 --link leaf-1-eth1
        sudo clab tools vxlan create --remote 172.10.10.103 --id 20 --link leaf-1-eth2
        sudo clab tools vxlan create --remote 172.10.10.104 --id 30 --link leaf-1-eth3
        sudo clab tools vxlan create --remote 172.10.10.104 --id 40 --link leaf-1-eth4

    - name: build leaf-2 vxlans
      hosts: leaf-2
      shell: |
        sudo clab tools vxlan create --remote 172.10.10.104 --id 10 --link leaf-2-eth1
        sudo clab tools vxlan create --remote 172.10.10.104 --id 20 --link leaf-2-eth2
        sudo clab tools vxlan create --remote 172.10.10.103 --id 30 --link leaf-2-eth3
        sudo clab tools vxlan create --remote 172.10.10.103 --id 40 --link leaf-2-eth4

    - name: build spine-1 vxlans
      hosts: spine-1
      shell: |
        sudo clab tools vxlan create --remote 172.10.10.101 --id 10 --link spine-1-eth1
        sudo clab tools vxlan create --remote 172.10.10.101 --id 20 --link spine-1-eth2
        sudo clab tools vxlan create --remote 172.10.10.102 --id 30 --link spine-1-eth3
        sudo clab tools vxlan create --remote 172.10.10.102 --id 40 --link spine-1-eth4

    - name: build spine-2 vxlans
      hosts: spine-2
      shell: |
        sudo clab tools vxlan create --remote 172.10.10.102 --id 10 --link spine-2-eth1
        sudo clab tools vxlan create --remote 172.10.10.102 --id 20 --link spine-2-eth2
        sudo clab tools vxlan create --remote 172.10.10.101 --id 30 --link spine-2-eth3
        sudo clab tools vxlan create --remote 172.10.10.101 --id 40 --link spine-2-eth4


