---
- name: Run git pull and containerlab deployments
  hosts: sonic_nodes
  become: true
  tasks:
    - name: git pull to update repo on each node
      command: git pull
      args:
        chdir: /home/cisco/sonic-dcloud
      ignore_errors: yes

    # - name: run containerlab deploy
    #   command: mv /etc/sonic/frr/bgpd.conf /etc/sonic/frr/bgpd.conf.bak
    #   args:
    #     creates: /etc/sonic/frr/bgpd.conf.bak
    #   ignore_errors: yes
    #   register: backup_result


